language: node_js
node_js:
  - "8"

cache: npm

branches:
  only:
    - master

# before_script:
#   - npm install -g firebase-tools
#   - npm install -g @angular/cli
#
# script:
#   - ng build --prod --aot
#
# after_success:
#   - firebase deploy --token $FIREBASE_TOKEN
install:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

jobs:
  include:
    - stage: test
      script: ng test
#     - stage: build
#       script: ng build --prod --aot
#     - stage: deploy
#       script: firebase deploy --token $FIREBASE_TOKEN