language: node_js
node_js:
  - "8"

cache: npm

branches:
  only:
  - developer

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod --aot

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  slack: makeit-espacio:ubMTKCxi0L8ihePJmUb1lbrz